"""create mealplan recipes table

Revision ID: 7958baf0d06b
Revises: 9ea966409ffb
Create Date: 2021-08-03 17:37:47.301441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7958baf0d06b'
down_revision = '9ea966409ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MealplanRecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mealplanId', sa.Integer(), nullable=False),
    sa.Column('recipeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mealplanId'], ['Mealplans.id'], ),
    sa.ForeignKeyConstraint(['recipeId'], ['Recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MealplanRecipes')
    # ### end Alembic commands ###
