"""create ingredient model

Revision ID: d7505f467745
Revises: f2bb525aefcd
Create Date: 2021-07-27 20:16:57.740404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7505f467745'
down_revision = 'f2bb525aefcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipeId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['recipeId'], ['Recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ingredients')
    # ### end Alembic commands ###
